import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})

export class SelectoresService {

  menu_estadisitca: string = "Estadistica"
  menu_boletin_op_dirop: string = "Boletin_Dirop"
  dicte : string = "dicte"
  insitop : string = "insitop"
  evento_relevante:string = "evento_relevante"
  q5 :string = "q5"
  menu_eventos: string = "Eventos"
  menu_users: string = "Users"
  menu_fuera_combate: string = "Fuera_Combate"

  alertas_ingreso: string = "alertas_ingreso"
  alertas_listado: string = "alertas_listados"
  planilla_alertas: string = "planilla_alertas"

  menu_menu_estadistica: boolean = false
  menu_menu_eventos: boolean = false
  menu_menu_user: boolean = false
  menu_menu_fuera_combate: boolean = false

  menu_menu_alerta: boolean = false
  menu_menu_alerta_listado: boolean = false
  menu_menu_planilla_alertas: boolean = false

  menu_resaltantes_boletin_per : boolean = false
  menu_evento_relevante : boolean = false

  menu_q5 : boolean = false

  coordenadas_lat_g:number = 0
  coordenadas_lat_m:number = 0
  coordenadas_lat_s:number = 0

  coordenadas_log_g:number = 0
  coordenadas_log_n:number = 0
  coordenadas_log_s:number = 0

  lati:string=""
  loti:string=""

  //menu 
  nemu_row_estadisitca: string = "row_estadisitca"
  nemu_row_q5:string= "row_q5"
  row_insitop : string = "row_insitop"
  row_evento_relevante:string = "row_evento_relevante"
  nemu_row_eventos: string = "row_eventos"
  nemu_row_user: string = "row_user"
  nemu_row_fuera_combate: string = "row_fuera_combate"

  nemu_row_alerta: string = "row_alerta"
  nemu_row_alerta_listado: string = "row_alerta_listado"
  nemu_row_planilla_alertas: string = "row_planilla_alertas"
  nemu_row_dicte : string = "nemu_row_dicte"
  menu_menu_movimientos: boolean = false
  menu_menu_dicte : boolean = false
  movimientos_menu : string = "movimientos"
  nemu_row_movimientos : string = "row_movimientos"


  menu_menu_inventarios: boolean = false
  inventarios_menu : string = "inventarios"
  nemu_row_inventarios : string = "row_inventarios"

  nemu_row_aetcr : string = "row_aetcr"
  nemu_aetcr: string = "aetcr"
  nemu_row_plazos : string = "row_plazos"
  row_boletin_op_dirop : string = "row_boletin_op_dirop"
  row_medallas : string = "row_medallas"
  ingreso_medallas : string = "medallas"
  plazos_m : string = "plazos"
  medallas_m:string = "medallas"

  // personal
  personal_menu: string = "personal_nenu"
  menu_menu_personal : boolean = false
  menu_menu_aetcr: boolean = false
  menu_menu_plazos : boolean = false
  boletin_op_dirop_menu : boolean = false
  menu_menu_medallas : boolean = false
  menu_menu_insitop : boolean = false
  nemu_row_personal : string = "row_personal"
  img_personal :Boolean = false
  img_personal_listado :Boolean = false

  img_activa_pdf:Boolean = false
  img_activa_mapa_resultados :Boolean = false
  img_acargar_resultyados:Boolean = false
  img_cargue_eventos_div :Boolean = false
  img_listado_eventos :Boolean = false
  img_mapa_eventos :Boolean = false
  img_creacion_usurios:Boolean =  false
  img_fuera_combate:Boolean =  false
  img_listado_anexo_1:boolean = false
  img_estadistica_anexo_1:boolean = false
  
  img_alerta:Boolean =  false
  img_alerta_listado:Boolean =  false
  img_planilla_alertas:Boolean =  false

  img_listado_aetcr :Boolean =  false
  img_mapa_aetcr:Boolean =  false

  img_movimientos:Boolean =  false
  img_inventarios:Boolean =  false
  img_creacion_aetcr:Boolean =  false
  img_listado_inventarios:Boolean =  false
  img_coordinadores_movimientos:Boolean =  false
  
  img_activa_resaltantes_boletin:Boolean =  false

  img_plasos_sin_asignar:Boolean =  false
  img_plasos_signados:Boolean =  false
  img_plasos_cumplidos:Boolean =  false
  img_plazos_cdte:Boolean =  false
  img_validacion_plazos:Boolean =  false
  img_ingreso_medallas:Boolean =  false
  img_listado_medallas :Boolean =  false
  img_seguimiento_plazos_c:boolean =  false
  img_BoletinDirop:boolean =  false

  // listas para los resultados
  unidad_selecionada_resultados: string[] = ["MENORES RECUPERADOS","CAPTURAS", "SOMETIMIENTOS A LA JUSTICIA","PRESENTACIONES VOLUNTARIAS", "MDOM"]
  unidad_selecionada_resultados_tropas:string[]=["ASESINADOS", "HERIDOS"]
  unidad_selecionada_resultados_armamento:string[]=["ARMAS DE LARGO ALCANCE", "ARMAS DE CORTO ALCANCE", "ARMAS DE ACOMPAÑAMIENTO", "MUNICIONES"]
  combates_a_selecionar:string[]=["COMBATES POSITIVOS", "COMBATES NEGATIVOS", "COMBATES SIN RESULTADOS", "COMBATES"]
  ataque_fuerza_publica:string[]=["ATAQUE FUERZA PUBLICA","HOSTIGAMIENTOS", "ASONADAS", "ATAQUES DRONS",'ACTIVACIÓN ARTEFACTO EXPLOSIVO', 'ACTIVACIÓN ZONA MINADA', 'ACTO DE TERRORISMO', 'ACTO DE TERRORISMO EN CONTRA DE INFRAESTRUCTURA CRITICA', 'ACTO DE TERRORISMO EN CONTRA DE POBLACIÓN CIVIL', 'ACTO DE TERRORISMO EN CONTRA DE PROPIAS TROPAS']
  material_explosivos:string[]=["NEUTRALIZACIÓN TERRORISTA", "ARTEFACTOS EXPLOSIVOS Und","A.E.I","MAP (Mina Anti Persona)", "EXPLOSIVOS kg", "EXPLOSIVOS m", "EXPLOSIVOS Und", "CORDÓN DETONANTE m", "MECHA LENTA m", "MEDIOS DE LANZAMIENTOS", "DETONADORES ELÉCTRICOS", "DETONADORES ANELÉCTRICOS" ]

  narcotrafico_lista:string[]=["COCAÍNA Kg", "MARIHUANA Kg","PBC Kg","HEROHINA Kg","BASUCO Kg","DROGAS SINTETICAS und", "LAB. CLORHIDRATO DE COCAINA","LAB. PASTA O BASE DE COCA","LAB. MORFINA Y HEROINA", "SEMILLEROS","MATAS DE COCA EN SEMILLEROS", "INSUMOS SOLIDOS Kg", "INSUMOS LIQUIDOS Gal", "COMBUSTIBLES NARCOTRAFICO Gal", "COCAÍNA EN PROCESO", "PASTA DE COCA EN PROCESO"]

  economias_ilicitas:string[]=["LIBERADOS", "RESCATADOS", "INCAUTACION DE PESOS COLOMBIANOS", "INCAUTACION DE DOLARES", "INCAUTACION DE EUROS", "INCAUTACIÓN DE MUEBLES", "INCAUTACIÓN DE INMUEBLES", "INCAUTACIÓN DE VEHICULOS"]

  afectaciones_oleoducto:string[]=["AFECTACIONES AL OLEODUCTO", "VÁLVULAS", "REFINERIAS","PISCINAS"," ABOYADURA", "APIQUE", "ROTURA","SABOTAJE AL OLEODUCTO", "PETROLEO"]
  
  afectaciones_a_la_mineria:string[]=["YACIMIENTOS MINEROS", "CAPTURAS MINERIA", "MENORES RECUPERADOS EN MINERIA", "UNIDAD MINERA PRODUCCIÓN", "MAQUINARIA PESADA", "TRACTOR CON URUGA - BULDOCER(ES)", "EXCAVADORAS", "RETROEXCAVADORAS", "DRAGAS", "MAQUINARIA AMARILLA", "MEDIOS DE TRANSPORTE", "MOTORES", "COMBUSTIBLES EN MINERIA", "EXPLOSIVOS MINERIA kg", "EXPLOSIVOS MINERIA m", "EXPLOSIVOS MINERIA Und", "COLTAN"] 

  afectaciones_al_contranando:string[]=["CAPTURAS CONTRABANDO","MENORES DE EDAD EN CONTRABANDO", "COMBUSTIBLES CONTRABANDO", "GASOLINA CONTRABANDO", "ACPM CONTRABANDO", "VEHICULOS DE CONTRABANDO", "INSUMOS LIQUIDOS DE CONTRABANDO", "INSUMOS SOLIDOS DE CONTRABANDO", "SEMOVIENTES DE CONTRABANDO"]
  
  loe_amazonia:string[]=["CAPTURAS LOE AMAZONÍA", "PLÁNTULAS SEMBRADAS", "INCAUTACIÓN MADERA M3", "ESPECIES ANIMALES INCAUTADOS"]

  otro:string[]=["DEPOSITOS ILEGALES", "PROSELITISMO", "CAMPAMENTOS"]
  
  //CARGOS DE LA DIRECCION DE OPERACIONES
  cargos:string[]=["DIRECTOR DE OPERACIONES", "OFICIAL COE", "SUBOFICIAL COE", "OFICIAL DE ESTADISTICA", "SUBOFICIAL DE ESTADISTICA", "OFICIAL AETCR", "SUBOFICIAL AETCR", "AYUDANTE", "PERSONAL", "ARCHIVO", "ESTIMULOS OPERACIONALES", "EVALUACION Y SEGUIMIENTO", "DISEÑO GRAFICO", "ENLACE COING", "MOVIMIENTOS TERRESTRES", "INFRAESTRUCTURA", "SEGUIMIENTO DIV01", "SEGUIMIENTO DIV02", "SEGUIMIENTO DIV03", "SEGUIMIENTO DIV04", "SEGUIMIENTO DIV05", "SEGUIMIENTO DIV06", "SEGUIMIENTO DIV07", "SEGUIMIENTO DIV08" , "SEGUIMIENTO DAVAA",  "SEGUIMIENTO DIVFE", "SEGUIMIENTO FUERZAS DE TAREA", "ENLACE DILEA" ]
  
  das_general_ejc:string[]=[]
  
  
  // informadion de dipse

  img_listado_usuarios:boolean = false
  img_CalendarioPlazosComponent:boolean = false
  img_informacion_evento_relevante:boolean = false
  img_informacion_q5:boolean = false
  img_DescargarQ5MenuComponent:boolean=false
  img_das_res_ejc:boolean=false
  img_VerEventosRelevantesComponent:boolean =false
  img_informacion_insitop :boolean = false
  img_reporte_insitop :boolean = false 
  img_pasos_fronterizos :boolean = false 
  listado:string[] =  ["estadistica", "estadistica_pdf", "cargue_eventos_div", "listado_eventos", "anexo_1", "mapa_eventos", "creacion_usurio", "listado_usuarios", "alertas_ingreso", "alertas_listados", "planilla_alertas", "---", "mapa_alerta", "PlanillaMovimientoComponent", "documentos_movimientos", "coordinadores_movimientos", "estadistica_movimientos", "ingreso_inventarios","ingreso_personal", "listado_personal", "listado_inventarios" , "listado_anexo_1", "estadistica_anexo_1", "eventos_resaltantes_boletin", "mapa_resultados", "ingreso_aetcr", "listado_aetcr", "mapa_aetcr", "plasos_sin_asignar", "plasos_signados", "plasos_cumplidos", "plazos_cdte", "validacion_plazos", "ingreso_medallas", "seguimiento_plazos_c", "listado_medallas", "CalendarioPlazosComponent", "informacion_insitop", "reporte_insitop","PasosFronterizosComponent", "GuardarEventosRelevantesComponent","VerEventosRelevantesComponent", "BoletinDirop", "RegistroQ5Component", "das_res_ejc"]

  nit_ejc:string[] =  ["NIT de Ejército", "NO APLICA"]
  unidad_a_que_pertenece:string[] =  ["EJÉRCITO NACIONAL DE COLOMBIA"]
  clasificacion_de_la_novedad:string[] =  ["Accidente", "Incidente", "Otro Evento"]
  Si_eligio_otro_diga_cual:string[] =  ["Agresión interna", "Agresión externa", "Lesión autoifligida"]
  tipo_de_vincualcion:string[] =  ["MILITAR/POLICIA", "PERSONAL CIVIL PLANTA /NO UNIFORMADO", "CONTRATISTAS", "CONTRATISTAS", "SUBCONTRATISTAS", "ALUMNOS", "VISITANTES", "PROVEEDORES"]

  jefactura:string[] =  ["COEJE", "JEMGF", "JEMOP", "JEMPP", "SECEJ", "JEIMI", "NA"]
  
  comando:string[] =  ["CAAID", "CACIM", "CAFUE" ,"CAIMI" ,"CAOCC" ,"CAOUR" ,"CCOES" ,"CEDOC" ,"CEMAI" ,"CGFM" ,"COING" ,"COLOG" ,"COPER" ,"COREC" ,"NA"]
  fuerza_tarea:string[] =  ["FUDAT" ,"FUDRA1" ,"FUDRA2" ,"FUDRA3" ,"FUDRA4" ,"NA"]
  cede:string[]=["CEDE1" ,"CEDE2" ,"CEDE3" ,"CEDE4" ,"CEDE5" ,"CEDE6" ,"CEDE7" ,"CEDE8" ,"CEDE9" ,"CEDE10" ,"CEDE11" ,"NA"]
 
  brigada:string[]=["BR01"	,"BR02"	,"BR03"	,"BR04"	,"BR05"	,"BR06"	,"BR07"	,"BR08"	,"BR09"	,"BR10"	,"BR11"	,"BR12"	,"BR13"	,"BR14"	,"BR15"	,"BR16"	,"BR17"	,"BR18"	,"BR22"	,"BR23"	,"BR26"	,"BR27"	,"BR28"	,"BR29"	,"BR30"	,"BR31"	,"BRAAID1"	,"BRAAID2"	,"BRCIM1"	,"BRCIM2 "	,"BRCNA"	,"BRCOM"	,"BRCON"	,"BRFER"	,"BRIAV25"	,"BRIAV32"	,"BRIAV33"	,"BRICO"	,"BRIER "	,"BRIMI1"	,"BRIMI2 "	,"BRING "	,"BRLOG1"	,"CEC"	,"CEDOE "	,"CEMAL"	,"CEMIL"	,"CENAE"	,"CENAG"	,"CEO"	,"DATRA "	,"DESTA "	,"DIACO "	,"DIADA"	,"DIADI"	,"DIADQ "	,"DIAFI "	,"DIATE"	,"DICAN"	,"DICER"	,"DICMI "	,"DICOO"	,"DICOR "	,"DICTE"	,"DIDAE"	,"DIDEF "	,"DIDEH"	,"DIDEM"	,"DIDEP"	,"DIDIP "	,"DIDOH "	,"DIEDU "	,"DIESP "	,"DIETE "	,"DIFAB"	,"DIGEC "	,"DIGED"	,"DIGEH"	,"DIGEI "	,"DIGEP"	,"DIGMI"	,"DILEA "	,"DINCO "	,"DINEG "	,"DIOEE"	,"DIORG"	,"DIPAI"	,"DIPAP "	,"DIPCO"	,"DIPDA"	,"DIPED"	,"DIPEI"	,"DIPEL "	,"DIPEP "	,"DIPER "	,"DIPIC"	,"DIPIE "	,"DIPLE "	,"DIPLI "	,"DIPLO"	,"DIPOC"	,"DIPOE"	,"DIPOH"	,"DIPOJ "	,"DIPSE"	,"DIPSO"	,"DIPTE"	,"DIREC "	,"DIRIC "	,"DIROP"	,"DISAN"	,"DISDI "	,"DISEO"	,"DISEP"	,"DISEV "	,"DISFI "	,"DISIC "	,"DISIL "	,"DITEC "	,"DITER"	,"DOCNA"	,"REGFE1"	,"REGFE2"	,"REGFE3"	,"NA"
]
  unidad_diper:string[]=["BAAAS"	,"BAABS1"	,"BAABS2"	,"BAACA1"	,"BAADA1"	,"BAADA2"	,"BAAID1"	,"BAAID2"	,"BAAID3"	,"BAAID4"	,"BAAID5"	,"BAAID6"	,"BAAID6"	,"BAAID7"	,"BAAID8"	,"BAAV1"	,"BAAV2"	,"BAAV3"	,"BAAV4"	,"BAAV5"	,"BACAC"	,"BACCE"	,"BACIB"	,"BACIF 1"	,"BACIF 2"	,"BACIF 3"	,"BACIF 4"	,"BACIF 5"	,"BACIM 1"	,"BACIM 2"	,"BACIM 3"	,"BACIM 4"	,"BACIM 5"	,"BACIM 6"	,"BACIM 7"	,"BACIM 8"	,"BACIM 9"	,"BACN1"	,"BACN2"	,"BACN3"	,"BACN4"	,"BACOA"	,"BACOM1 "	,"BACOM2 "	,"BACOM3"	,"BACSI "	,"BACUC"	,"BADRA1"	,"BADRA2"	,"BADRA3"	,"BADRE1"	,"BAEEV1"	,"BAEEV10"	,"BAEEV12"	,"BAEEV13"	,"BAEEV14"	,"BAEEV15"	,"BAEEV16"	,"BAEEV17"	,"BAEEV18"	,"BAEEV19"	,"BAEEV2"	,"BAEEV20"	,"BAEEV21"	,"BAEEV22"	,"BAEEV3"	,"BAEEV4"	,"BAEEV5"	,"BAEEV6"	,"BAEEV7"	,"BAEEV8"	,"BAEEV9"	,"BAFLA "	,"BAFUR1"	,"BAFUR2"	,"BAFUR3"	,"BAFUR4"	,"BAFUR5"	,"BAFUR6"	,"BAFUR7"	,"BAFUR8"	,"BAGAL"	,"BAGCI "	,"BAGOP "	,"BAIDI "	,"BAIME 1"	,"BAIME 2"	,"BAIME 3"	,"BAIME 4"	,"BAIME 5"	,"BAIMI 1"	,"BAIMI 2"	,"BAIMI 3"	,"BAIMI 4"	,"BAIMI 5"	,"BAIMI 6"	,"BAIMI 7"	,"BAIMI 8"	,"BAINT"	,"BAJES"	,"BALOC"	,"BAMAD"	,"BAMAI"	,"BAMAM"	,"BAMAN"	,"BAMAR"	,"BAMAV1"	,"BAMAV2"	,"BAMAV3"	,"BAMAV4"	,"BAMCE"	,"BAMGU"	,"BAMHE"	,"BAMJO"	,"BAMMA"	,"BAMOG"	,"BAMRO"	,"BAMRU"	,"BAMUR"	,"BAOEA"	,"BAOPE1"	,"BAOPE2"	,"BAPAL"	,"BAPOM12"	,"BAPOM18"	,"BAPOM30"	,"BAPOM7"	,"BAPOP"	,"BAS03"	,"BAS07"	,"BAS1"	,"BAS10"	,"BAS16"	,"BAS18 "	,"BAS2"	,"BAS21"	,"BAS22"	,"BAS23"	,"BAS28"	,"BAS29"	,"BAS30"	,"BAS5"	,"BAS6"	,"BAS8"	,"BASAC"	,"BASAM"	,"BASAN"	,"BASBA"	,"BASCI "	,"BASCN"	,"BASCO"	,"BASDO"	,"BASEC 1"	,"BASEC 2"	,"BASEC 3"	,"BASEC 4"	,"BASEC 5"	,"BASEM"	,"BASEN"	,"BASGO"	,"BASIM "	,"BASMI 1"	,"BASMI 2"	,"BASMI 3"	,"BASMI 4"	,"BASMI 5"	,"BASMO"	,"BASOE"	,"BASPA25"	,"BASPC04"	,"BASPC09"	,"BASPC11"	,"BASPC12"	,"BASPC13"	,"BASPC14"	,"BASPC15"	,"BASPC17 "	,"BASPC26"	,"BASPC27"	,"BASRO"	,"BATAC"	,"BATAD"	,"BATAM09"	,"BATAR"	,"BATEN"	,"BATLA"	,"BATOT1"	,"BATOT10"	,"BATOT102"	,"BATOT107"	,"BATOT109"	,"BATOT11"	,"BATOT11"	,"BATOT111"	,"BATOT112"	,"BATOT12"	,"BATOT122"	,"BATOT13 "	,"BATOT142"	,"BATOT15"	,"BATOT155"	,"BATOT17"	,"BATOT18"	,"BATOT180"	,"BATOT19"	,"BATOT2"	,"BATOT20"	,"BATOT21"	,"BATOT22"	,"BATOT23"	,"BATOT24"	,"BATOT250"	,"BATOT26"	,"BATOT28"	,"BATOT28"	,"BATOT29"	,"BATOT3"	,"BATOT30"	,"BATOT32"	,"BATOT37"	,"BATOT4"	,"BATOT47"	,"BATOT5"	,"BATOT51"	,"BATOT6"	,"BATOT63"	,"BATOT66"	,"BATOT70"	,"BATOT77"	,"BATOT87"	,"BATOT9"	,"BATOT94"	,"BATOT99"	,"BATRA1"	,"BATRA2"	,"BECOM"	,"BETRA"	,"BFER1"	,"BFER2"	,"BFER3"	,"BFER4"	,"BFER5"	,"BIADE"	,"BIAHE"	,"BIALB"	,"BIAMA"	,"BIANG23"	,"BIAVA"	,"BIAYA"	,"BIBAR"	,"BIBEM"	,"BIBOL"	,"BIBOM"	,"BIBOY"	,"BIBYA"	,"BICAB"	,"BICAI"	,"BICAL"	,"BICAM"	,"BICAR"	,"BICAS"	,"BICAZ"	,"BICIS"	,"BICOD"	,"BICOL"	,"BICOL3  "	,"BICON50"	,"BICON51"	,"BICON52"	,"BICON53"	,"BICOR"	,"BIDES"	,"BIFRA56"	,"BIGAM "	,"BIGIR"	,"BIGOH"	,"BIGUE"	,"BIGUP"	,"BIJOS"	,"BIJUA"	,"BIJUL"	,"BIJUN"	,"BILAC"	,"BILOP"	,"BILUD"	,"BIMAC"	,"BIMAG"	,"BIMEJ"	,"BIMUR"	,"BINAR"	,"BINGE "	,"BINSE "	,"BINUT"	,"BIOPE"	,"BIOSP"	,"BIPAR"	,"BIPAT"	,"BIPEB"	,"BIPIC"	,"BIPIG"	,"BIPIN"	,"BIRAN"	,"BIREY"	,"BIRIC"	,"BIRIF"	,"BIRNA"	,"BIROJ"	,"BIROK"	,"BIROR"	,"BIROV"	,"BISAN"	,"BISER"	,"BISOL "	,"BISUC"	,"BISUM "	,"BITER1"	,"BITER10"	,"BITER11"	,"BITER12"	,"BITER13"	,"BITER14"	,"BITER15"	,"BITER16"	,"BITER17"	,"BITER18"	,"BITER2"	,"BITER21"	,"BITER22"	,"BITER23"	,"BITER26"	,"BITER27"	,"BITER28"	,"BITER29"	,"BITER3"	,"BITER30"	,"BITER4"	,"BITER5"	,"BITER6"	,"BITER7"	,"BITER8"	,"BITER9"	,"BIVAR"	,"BIVEL"	,"BIVEN"	,"BIVER"	,"BIVOL"	,"BMMA1"	,"BMMA2"	,"BMMA3"	,"BMMA4"	,"BMMA5"	,"BMMA6"	,"BMMA7"	,"BMMA8"	,"BOAID"	,"BPM02"	,"BPM03"	,"BPM04"	,"BPM13"	,"BPM15"	,"BPM24"	,"BPM5"	,"BR05"	,"BR07"	,"BR1"	,"BR10"	,"BR11"	,"BR12"	,"BR13"	,"BR14"	,"BR15"	,"BR16"	,"BR17"	,"BR18"	,"BR2"	,"BR22"	,"BR23"	,"BR26"	,"BR27"	,"BR28"	,"BR29"	,"BR3"	,"BR30"	,"BR31"	,"BR4"	,"BR6"	,"BR8"	,"BR9"	,"BRAAC"	,"BRADA"	,"BRAID1"	,"BRAID2"	,"BRCIM1"	,"BRCIM2 "	,"BRCMI"	,"BRCNA"	,"BRCOM"	,"BRCON"	,"BRFER"	,"BRIAV25"	,"BRIAV32"	,"BRIAV33"	,"BRICO"	,"BRIER "	,"BRING "	,"BRLOG1 "	,"BRLOG2 "	,"CAAID"	,"CACIM "	,"CADCO"	,"CAFUE"	,"CAIMI "	,"CAOCC"	,"CAOUR"	,"CASPC1"	,"CASPC2"	,"CEAYG"	,"CEC"	,"CECAT"	,"CEDE1"	,"CEDE10"	,"CEDE11"	,"CEDE2"	,"CEDE3"	,"CEDE4"	,"CEDE5"	,"CEDE6 "	,"CEDE7"	,"CEDE8 "	,"CEDE9"	,"CEDOC "	,"CEDOE "	,"CEFER"	,"CEHEJ "	,"CEIGE"	,"CEMAI"	,"CEMIL"	,"CENAC ARAUCA"	,"CENAC ARMENIA"	,"CENAC AVIACIÓN"	,"CENAC BARRANQUILLA"	,"CENAC BUCARAMANGA"	,"CENAC BUENAVISTA"	,"CENAC CALI"	,"CENAC CANTÓN SUR"	,"CENAC CAREPA"	,"CENAC CEMIL"	,"CENAC CONVENIOS"	,"CENAC CUCUTA"	,"CENAC FACATATIVÁ"	,"CENAC FLORENCIA"	,"CENAC IBAGUÉ"	,"CENAC INGENIEROS"	,"CENAC INTELIGENCIA"	,"CENAC LETICIA"	,"CENAC MEDELLÍN"	,"CENAC MOCOA"	,"CENAC MONTERÍA"	,"CENAC NEIVA"	,"CENAC OPERACIONES ESPECIALES"	,"CENAC PASTO"	,"CENAC PERSONAL"	,"CENAC POPAYÁN"	,"CENAC PUENTE ARANDA (BOGOTÁ)"	,"CENAC PUERTO BERRIO"	,"CENAC PUERTO CARREÑO"	,"CENAC QUIBDÓ"	,"CENAC RECLUTAMIENTO"	,"CENAC SAN JOSÉ DEL GUAVIARE"	,"CENAC SANTA MARTA"	,"CENAC TELEMÁTICA"	,"CENAC TOLEMAIDA"	,"CENAC TUNJA"	,"CENAC USAQUEN (BOGOTÁ)"	,"CENAC VALLEDUPAR"	,"CENAC VILLAVICENCIO"	,"CENAC YOPAL"	,"CENAE "	,"CENAM"	,"CEO"	,"CGFM"	,"COACO1"	,"COACO2"	,"COACO3"	,"COATE "	,"COEJE"	,"COFIP"	,"COING "	,"COLOG"	,"COMEJ"	,"COMOL1"	,"COMOL2"	,"COMOL3"	,"COMOL4"	,"COOFE"	,"COPER "	,"COPSI02"	,"COPSI03"	,"COPSI04"	,"COPSI05"	,"COPSI06"	,"COPSI07"	,"COPSI08"	,"COPSI1"	,"COREC "	,"COTEF"	,"CPMET_DIV2"	,"CPMET_DIV8"	,"CPMET1"	,"CPMET11"	,"CPMET12"	,"CPMET13"	,"CPMET2"	,"CPMET4"	,"CPMET5"	,"CPMET6"	,"CPMET7"	,"CPMET8"	,"CPMET9"	,"DANTE"	,"DATRA "	,"DAVAA "	,"DESTA "	,"DETAP1"	,"DETAP10"	,"DETAP11"	,"DETAP12"	,"DETAP13"	,"DETAP14"	,"DETAP15"	,"DETAP16"	,"DETAP17"	,"DETAP18"	,"DETAP2"	,"DETAP22"	,"DETAP23"	,"DETAP26"	,"DETAP27"	,"DETAP28"	,"DETAP29"	,"DETAP3"	,"DETAP31"	,"DETAP4"	,"DETAP5"	,"DETAP6"	,"DETAP7"	,"DETAP8"	,"DETAP9"	,"DIACO "	,"DIADA"	,"DIADI"	,"DIADQ "	,"DIAFI "	,"DIATE"	,"DICAN"	,"DICER "	,"DICMI "	,"DICOE"	,"DICOI"	,"DICOO"	,"DICOR "	,"DICTE"	,"DIDAE"	,"DIDEF "	,"DIDEH"	,"DIDEM"	,"DIDEP"	,"DIDIP "	,"DIDOH "	,"DIEDU "	,"DIESP "	,"DIETE "	,"DIFAB "	,"DIGEC "	,"DIGED"	,"DIGEH"	,"DIGEI "	,"DIGEP"	,"DIGMI"	,"DILEA "	,"DINCO "	,"DINEG "	,"DIOEE"	,"DIORG"	,"DIPAI"	,"DIPAP "	,"DIPCO"	,"DIPDA"	,"DIPED"	,"DIPEI"	,"DIPEL "	,"DIPEP "	,"DIPER "	,"DIPIC"	,"DIPIE "	,"DIPLE "	,"DIPLI "	,"DIPLO"	,"DIPOC"	,"DIPOE"	,"DIPOH"	,"DIPOJ "	,"DIPSE"	,"DIPSO "	,"DIPTE"	,"DIREC "	,"DIRIC "	,"DIRIE"	,"DIROP"	,"DISAN "	,"DISDI "	,"DISEO"	,"DISEP"	,"DISEV "	,"DISFI "	,"DISIC "	,"DISIL "	,"DISTRITO1"	,"DISTRITO10"	,"DISTRITO11"	,"DISTRITO12"	,"DISTRITO13"	,"DISTRITO14"	,"DISTRITO15"	,"DISTRITO16"	,"DISTRITO17"	,"DISTRITO18"	,"DISTRITO19"	,"DISTRITO2"	,"DISTRITO20"	,"DISTRITO21"	,"DISTRITO22"	,"DISTRITO23"	,"DISTRITO24"	,"DISTRITO25"	,"DISTRITO26"	,"DISTRITO28"	,"DISTRITO29"	,"DISTRITO3"	,"DISTRITO30"	,"DISTRITO31"	,"DISTRITO32"	,"DISTRITO33"	,"DISTRITO34"	,"DISTRITO35"	,"DISTRITO36"	,"DISTRITO37"	,"DISTRITO38"	,"DISTRITO39"	,"DISTRITO4"	,"DISTRITO40"	,"DISTRITO41"	,"DISTRITO42"	,"DISTRITO43"	,"DISTRITO44"	,"DISTRITO45"	,"DISTRITO46"	,"DISTRITO47"	,"DISTRITO48"	,"DISTRITO49"	,"DISTRITO5"	,"DISTRITO51"	,"DISTRITO52"	,"DISTRITO53"	,"DISTRITO54"	,"DISTRITO55"	,"DISTRITO56"	,"DISTRITO57"	,"DISTRITO58"	,"DISTRITO59"	,"DISTRITO6"	,"DISTRITO60"	,"DISTRITO61"	,"DISTRITO62"	,"DISTRITO7"	,"DISTRITO8"	,"DISTRITO9"	,"DITEC "	,"DITER"	,"DIV02"	,"DIV03 "	,"DIV05 "	,"DIV08 "	,"DIV1"	,"DIV4"	,"DIV6"	,"DIV7"	,"DIVFE"	,"DMBUG"	,"DMCAL"	,"DMGEM"	,"DMMED"	,"DMORI"	,"DMSOC"	,"DMTOL"	,"DOCNA"	,"EJAPI"	,"EJART"	,"EJEBE"	,"EJECA"	,"EJECO"	,"EJEMA"	,"EJEPO"	,"EJEYO"	,"EJUPA"	,"EMSUB"	,"EMSUB"	,"ESACE"	,"ESAJU"	,"ESART"	,"ESASA"	,"ESAVE "	,"ESCAB"	,"ESCEQ"	,"ESCOM"	,"ESDAE"	,"ESDIH"	,"ESERT"	,"ESFER"	,"ESICI"	,"ESIDE"	,"ESINF"	,"ESING"	,"ESLAN"	,"ESLOG"	,"ESMAI"	,"ESMIC"	,"ESMIC"	,"ESPAM"	,"ESPOM"	,"ESPRO"	,"ESPRO"	,"ESTIR"	,"FTCTITAN"	,"FTJUP"	,"FTMAR"	,"FTSUM"	,"FUDRA1"	,"FUDRA2"	,"FUDRA3"	,"FUDRA4"	,"FUNUP"	,"FUPEG"	,"FURON"	,"FUTAM"	,"FUTAP"	,"FUTZE"	,"FUVUL"	,"GAOCC"	,"GBMAT"	,"GGANT"	,"GGARA"	,"GGARI"	,"GGBCA"	,"GGBOY"	,"GGCAQ"	,"GGCAR"	,"GGCAS"	,"GGCAU"	,"GGCES"	,"GGCHO"	,"GGCOR"	,"GGCUN"	,"GGENA"	,"GGENA1"	,"GGENA2"	,"GGGUA"	,"GGHUI"	,"GGMAG"	,"GGMET"	,"GGNAR"	,"GGNSA"	,"GGPUT"	,"GGRIO"	,"GGRIS"	,"GGSAN"	,"GGTOL"	,"GGVAL"	,"GMARD1"	,"GMARD2"	,"GMARD3"	,"GMARD4"	,"GMARD5"	,"GMARD6"	,"GMARD7"	,"GMARD8"	,"GMCAB"	,"GMCOR"	,"GMGDC"	,"GMMAZ"	,"GMRIN"	,"GMRON"	,"GMRPI"	,"GMSIL"	,"GMTEQ "	,"JEMGF "	,"JEMOP "	,"JEMPP"	,"OADAS"	,"OSMEJ"	,"RECON"	,"REGFE1"	,"REGFE2"	,"REGFE3"	,"SECEJ"	,"USA_BRIM1 "	,"USA_BRIM2 "	,"ZONA1"	,"ZONA11"	,"ZONA13"	,"ZONA15"	,"ZONA2"	,"ZONA3"	,"ZONA4"	,"ZONA5"	,"ZONA6"	,"ZONA7"	,"ZONA8"	,"ZONA9"
]


eps_que_pertenece:string[]=["DIRECCIÓN GENERAL SANIDAD MILITAR (PERSONAL MILITAR)"	,"CAJA DE COMPENSACIÓN FAMILIAR CAMACOL - COMFAMILIAR CAMACOL"	,"CAJA DE COMPENSACIÓN FAMILIAR DE ANTIOQUIA 'COMFAMA'"	,"CAJA DE COMPENSACIÓN FAMILIAR DE CARTAGENA 'COMFAMILIAR CARTAGENA'"	,"CAJA DE COMPENSACIÓN FAMILIAR DE BOYACÁ 'COMFABOY'"	,"CAJA DE COMPENSACIÓN FAMILIAR DE CÓRDOBA 'COMFACOR'"	,"CAJA DE COMPENSACIÓN FAMILIAR - CAFAM"	,"CAJA DE COMPENSACIÓN FAMILIAR DE LA GUAJIRA"	,"CAJA DE COMPENSACIÓN FAMILIAR DE HUILA - COMFAMILIARHILA"	,"CAJA DE COMPENSACIÓN FAMILIAR DE NARIÑO"	,"CAJA DE COMPENSACIÓN FAMILIAR FENALCO - COMFENALCO QUINDÍO"	,"CAJA SANTANDEREANA DE SUBSIDIO FAMILIAR - CAJASAN"	,"CAJA DE COMPENSACIÓN FAMILIAR DE FENALCO SECCIONAL SANTANDER"	,"CAJA DE COMPENSACIÓN FAMILIAR DE SUCRE - COMFASUCRE"	,"CAJA DE COMPENSACIÓN FAMILIAR DE BARRANCABERMEJA - CAFABA"	,"CAJA DE COMPENSACIÓN FAMILIAR DE FENALCO DEL TOLIMA - COMFENALCO"	,"CAJA DE COMPENSACIÓN FAMILIAR DEL NORTE DE SANTANDER - FAMISALUD COMFANORTE A.R.S"	,"CAJA DE COMPENSACIÓN FAMILIAR DEL ORIENTE COLOMBIANO - COMFAORIENTE"	,"CAJA DE COMPENSACIÓN FAMILIAR DE CUNDINAMARCA COMFACUNDI-ARS UNICAJAS COMFACUNDI"	,"CAJA DE COMPENSACIÓN FAMILIAR CAJACOPI ATLÁNTICO"	,"CAJA COLOMBIANA DE SUBSIDIO  FAMILIAR-COLSUBSIDIO"	,"CAJA DE COMPENSACIÓN FAMILIAR COMFAMILIAR CHOCO"	,"CAJA DE COMPENSACIÓN FAMILIAR DEL CAQUETA"	,"EMPRESAS PÚBLICAS DE MEDELLÍN DEPARTAMENTO MÉDICO ANTIOQUIA MEDELLIN"	,"FONDO DE PASIVO SOCIAL DE FERROCARRILES NACIONALES DE COLOMBIA"	,"COLMEDICA E.P.S"	,"SALUD TOTAL S.A. ENTIDAD PROMOTORA DE SALUD"	,"CAFÉSALUD EPS"	,"SANITAS S.A. EPS"	,"COMPENSAR E.P.S"	,"COMFENALCO ANTIOQUIA"	,"SUSALUD EPS"	,"COMFENALCO VALLE E.P.S."	,"SALUDCOOP EPS"	,"HUMANA VIVIR EPS"	,"SALUD COLPATRIA E.P.S"	,"COOMEVA E.P.S. S.A."	,"EPS FAMISANAR LTDA"	,"SERVICIO OCCIDENTAL DE SALUD SOS EPS"	,"CAJA DE PREVENSIÓN SOCIAL DE COMUNICACIONES 'CAPRECOM'"	,"CONVIDA 'A.R.S. CONVIDA'"	,"CRUZ VLANCA EPS S.A."	,"CAJA DE PREVENSIÓN SOCIAL Y SEGURIDAD DEL CASANARE - CAPRESOCA - E.P.S."	,"SOLIDARIA DE SALUD SOLSALUD ENTIDAD PROMOTORA DE SALUD DEL RÉGIMEN CONTRIBUTIVO Y"	,"CALISALUD ENTIDAD PROMOTORA DE SALUD"	,"ENTIDAD PROMOTORA DE SALUD CONDOR S.A. ADMINISTRADORA DEL RÉGIMEN SUBSIDIADO"	,"SELVASALUD S.A. EPS ARL"	,"SALUDVIDA E.P.S. S.A."	,"SALUDCOLOMBIA"	,"RED SALUD ATENCIÓN HUMANA E.P.S S.A"	,"NUEVA EPS"	,"MULTIMEDICA EPS"	,"GOLDEN GROUP EPS"	,"ASOCIACIÓN DE CABILDOS INDÍGENAS DEL CESAR Y GUAJIRA 'DUSAKAWI A.R.S.I.'"	,"ASOCIACIÓN DE CABILDOS DEL RESFUARDO INDÍGENA ZENÚ DE SAN ADRES DE SOTAVENTO"	,"ASOCIACIÓN INDÍGENA DEL CAUCA AIC-EPS-I"	,"ANAS WAYUU EPS INDIGENA"	,"ENTIDAD PROMOTORA DE SALUD MALLAS EPSI"	,"PIJAOS SALUD EPSI"	,"CAPITAL SALUD EPS"	,"EMPRESA MUTUAL PARA EL DESARROLLO INTEGRAL DE LA SALUD E.S.S. 'EMDISALUD'"	,"COOPERATIVA DE SALUD Y DESARROLLO INTEGRAL ZONA SUR ORIENTAL DE CARTAGENA LTDA."	,"ASOCIACIÓN  MUTUAL LA ESPERANZA 'ASMET SALUD'"	,"ASOCIACIÓN MUTUAL BARRIOS UNIDOS DE QUIBDO AMBUQ ARS"	,"ECOOPSOS EMPRES SOLIDARIA DE SALUD"	,"ASOCIACIÓN MUTUAL EMPRESA SOLIDARIA DE SALUD EMSSANAR ESS"	,"ESS COMPARTA"	,"ASOCIACIÓN MUTUAL SER EMPRESA SOLIDARIA DE SALUD ESS"	,"FUERZAS MILITARES - ARMADA"	,"FUERZAS MILITARES - FUERZA AEREA"	,"FUERZAS MILITARES - EJERCITO"	,"FUERZAS MILITARES - HOSPITAL MILITAR CENTRAL"	,"POLICIA NACIONAL"	,"DIRECCION GENERAL DE SANIDAD DEL EJERCITO"]

arl_que_pertenece:string[]=["ASEGURADORA DE VIDA COLSEGUROS"	,"SEGUROS DE VIDA ALFA S.A."	,"LIBERTY SEGUROS DE VIDA "	,"SEGUROS DE VIDA DEL ESTADO S.A."	,"POSITIVA COMPAÑIA DE SEGUROS"	,"RIESGOS PROFESIONALES COLMENA S.A COMPAÑÍA DE SEGU"	,"BBVA SEGUROS DE VIDA COLOMBIA S.A"	,"COMPAÑÍA CENTRAL DE SEGUROS DE VIDA S.A."	,"COMPAÑIA SURAMERICANA ADMINISTRADORA DE RIESGOS PR"	,"LA EQUIDAD SEGUROS DE VIDA ORGANISMO COOP"	,"SEGUROS DE VIDA COLPATRIA S.A."	,"COMPAÑIA AGRICOLA DE SEGUROS DE VIDA S.A."	,"CIA. DE SEGUROS BOLIVAR S.A."	,"COMPAÑIA DE SEGUROS DE VIDA AURORA"	,"EJÉRCITO NACIONAL DE COLOMBIA"	,"FUERZA AÉREA COLOMBIANA"	,"ARMADA NACIONAL DE COLOMBIA"	,"POLICÍA NACIONAL DE COLOMBIA"	,"NO APLICA"
]
  
municipio_dipse:string[]=["ABEJORRAL"	,"ABREGO"	,"ABRIAQUI"	,"ACACIAS"	,"ACANDI"	,"ACEVEDO"	,"ACHI"	,"AGRADO"	,"AGUA DE DIOS"	,"AGUACHICA"	,"AGUADA"	,"AGUADAS"	,"AGUSTIN CODAZZI"	,"AIPE"	,"ALBAN"	,"ALBAN SAN JOSE"	,"ALBANIA"	,"ALBANIA"	,"ALBANIA (LA GUAJIRA)"	,"ALCALA"	,"ALDANA"	,"ALEJANDRIA"	,"ALGARROBO"	,"ALGECIRAS"	,"ALMAGUER"	,"ALMEIDA"	,"ALPUJARRA"	,"ALTAMIRA"	,"ALTAMIRA (HUILA)"	,"ALTO BAUDO"	,"ALTOS DEL ROSARIO"	,"ALVARADO"	,"AMAGA"	,"AMALFI"	,"AMBALEMA"	,"ANAPOIMA"	,"ANCUYA"	,"ANDAGOYA"	,"ANDALUCIA"	,"ANDES"	,"ANGELOPOLIS"	,"ANGOSTURA"	,"ANOLAIMA"	,"ANORI"	,"ANSERMA"	,"ANSERMANUEVO"	,"ANTIOQUIA (ANTIOQUIA"	,"ANZA"	,"ANZOATEGUI"	,"APARTADO"	,"APIA"	,"APULO"	,"AQUITANIA"	,"ARACATACA"	,"ARANZAZU"	,"ARATOCA"	,"ARATOGA"	,"ARBELAEZ"	,"ARBOLEDA"	,"ARBOLEDAS"	,"ARBOLETES"	,"ARCABUCO"	,"ARENAL"	,"ARGELIA (ANTIOQUIA)"	,"ARGELIA (CAUCA)"	,"ARGELIA (VALLE)"	,"ARIGUANI"	,"ARJONA"	,"ARMA"	,"ARMENIA (ANTIOQUIA)"	,"ARMENIA (QUINDIO)"	,"ARMERO"	,"ARROYOHONDO"	,"ASTREA"	,"ASTURIAS (VALLE)"	,"ATACO"	,"ATRATO (YUTO)"	,"AYAPEL"	,"BAGADO"	,"BAHIA SOLANO"	,"BAJO BAUDO"	,"BALBOA (CAUCA)"	,"BALBOA (RISARALDA)"	,"BARANOA"	,"BARAYA"	,"BARBACOAS"	,"BARBOSA"	,"BARBOSA (SANTANDER)"	,"BARCELONA (QUINDIO)"	,"BARICHARA"	,"BARRANCA DE UPIA"	,"BARRANCABERMEJA"	,"BARRANCAS"	,"BARRANCO DE LOBA"	,"BARRANQUILLA"	,"BECERRIL"	,"BELALCAZAR"	,"BELEN"	,"BELEN"	,"BELEN ANDAQUIES"	,"BELEN DE UMBRIA"	,"BELENCITO"	,"BELLAVISTA (MAGDALEN"	,"BELLO"	,"BELMIRA"	,"BELTRAN"	,"BERBEO"	,"BETANIA"	,"BETEITIVA"	,"BETULIA (ANT-COLOMBI"	,"BETULIA (SANT-COLOMB"	,"BITUIMA"	,"BOAVITA"	,"BOCHALEMA"	,"BOGOTA D.C"	,"BOJACA"	,"BOJAYA"	,"BOLIVAR"	,"BOLIVAR (ANTIOQUIA)"	,"BOLIVAR (CAUCA)"	,"BOLIVAR (VALLE)"	,"BOSCONIA"	,"BOYACA (BOYACA)"	,"BRICENO (ANTIOQUIA)"	,"BRICENO (BOYACA)"	,"BUCARAMANGA"	,"BUCARASICA"	,"BUENAVENTURA"	,"BUENAVISTA (BOYACA)"	,"BUENAVISTA (CORDOBA)"	,"BUENAVISTA (QUINDIO)"	,"BUENAVISTA (SUCRE)"	,"BUENOS AIRES"	,"BUESACO"	,"BUGA"	,"BUGALAGRANDE"	,"BURITICA"	,"BUSBANZA"	,"CABRERA"	,"CABRERA"	,"CABRERA (QUINDIO)"	,"CABUYARO"	,"CACERES"	,"CACHIPAY"	,"CACHIRA"	,"CACOTA"	,"CAICEDO"	,"CAICEDONIA"	,"CAIMITO"	,"CAJAMARCA (TOLIMA)"	,"CAJIBIO"	,"CAJICA"	,"CALAMAR"	,"CALARCA"	,"CALDAS (ANTIOQUIA)"	,"CALDAS (BOYACA)"	,"CALDAS (CALDAS)"	,"CALDONO"	,"CALI"	,"CALIFORNIA"	,"CALIMA(DARIEN)"	,"CALOTO"	,"CAMPAMENTO"	,"CAMPECHE"	,"CAMPO DE LA CRUZ"	,"CAMPOALEGRE"	,"CAMPOHERMOSO"	,"CANALETE"	,"CANASGORDAS"	,"CANDELARIA (ATLANTIC"	,"CANDELARIA (VALLE)"	,"CANTAGALLO"	,"CANTON DEL SAN PABLO"	,"CAPARRAPI"	,"CAPITANEJO"	,"CAQUEZA"	,"CARACOLI"	,"CARAMANTA"	,"CARCASI"	,"CAREPA"	,"CARMEN DE APICALA"	,"CARMEN DE ATRATO"	,"CARMEN DE CARUPA"	,"CARMEN DE VIBORAL"	,"CAROLINA"	,"Cartagena"	,"CARTAGENA (BOL.)"	,"CARTAGENA DE CHAIRA"	,"CARTAGENA DEL CHAIRA"	,"CARTAGO"	,"CASABIANCA"	,"CASTILLA LA NUEVA"	,"CAUCASIA"	,"CEPITA"	,"CERETE"	,"CERINZA"	,"CERRITO"	,"CERRO DE SAN ANTONIO"	,"CERTEGUI"	,"CHACHAGUI"	,"CHAGUANI"	,"CHALAN"	,"CHAPARRAL"	,"CHARALA"	,"CHARTA"	,"CHIA"	,"CHIGORODO"	,"CHIMA"	,"CHIMA (SANTANDER)"	,"CHIMICHAGUA"	,"CHINACOTA"	,"CHINAVITA"	,"CHINCHINA"	,"CHINU"	,"CHIPAQUE"	,"CHIPATA"	,"CHIQUINQUIRA"	,"CHIQUIZA"	,"CHIQUIZA"	,"CHIRIGUANA"	,"CHISCAS"	,"CHITA"	,"CHITAGA"	,"CHITARAQUE"	,"CHIVATA"	,"CHIVOLO"	,"CHIVOR"	,"CHOACHI"	,"CHOCONTA"	,"CICUCO"	,"CIENAGA (MAGDALENA)"	,"CIENAGA DE ORO"	,"CIENEGA"	,"CIMITARRA"	,"CIRCASIA"	,"CISNEROS"	,"CLEMENCIA"	,"COCONUCO"	,"COCORNA"	,"COELLO"	,"COGUA"	,"COLOMBIA"	,"COLON (NARINO)"	,"COLOSO"	,"COMBITA"	,"CONCEPCION"	,"CONCEPCION"	,"CONCORDIA"	,"CONCORDIA"	,"CONDOTO"	,"CONFINES"	,"CONSACA"	,"CONTADERO"	,"CONTRATACION"	,"CONVENCION"	,"COPACABANA"	,"COPER"	,"CORDOBA (BOLIVAR)"	,"CORDOBA (CALDAS)"	,"CORDOBA (NARINO)"	,"CORDOBA (QUINDIO)"	,"CORINTO"	,"COROMONO"	,"COROZAL"	,"CORRALES"	,"COTA"	,"COTORRA"	,"COVARACHIA"	,"COYAIMA"	,"CRAVO NORTE"	,"CUASPUD"	,"CUBARA"	,"CUBARRAL"	,"CUCAITA"	,"CUCUNUBA"	,"CUCUTA"	,"CUCUTILLA"	,"CUITIVA"	,"CUMARAL"	,"CUMBAL"	,"CUMBITARA"	,"CUNDAY"	,"CURILLO"	,"CURITI"	,"CURUMANI"	,"DABEIBA"	,"DAGUA"	,"DIBULLA"	,"DICATA"	,"DISTRACCION"	,"DOLORES"	,"DON MATIAS"	,"DOS QUEBRADAS"	,"DUITAMA"	,"DURANIA"	,"EBEJICO"	,"EL AGUILA"	,"EL BAGRE"	,"EL BANCO"	,"EL CAIRO"	,"EL CALVARIO"	,"EL CARMEN"	,"EL CARMEN (NTE SANTA"	,"EL CARMEN (SANTANDER"	,"EL CARMEN DE BOLIVAR"	,"EL CASTILLO"	,"EL CENTRO"	,"EL CERRITO"	,"EL CHARCO"	,"EL COCUY"	,"EL COLEGIO"	,"EL COPEY"	,"EL DONCELLO"	,"EL DORADO"	,"EL DOVIO"	,"EL ESPINO"	,"EL GUACAMAYO"	,"EL GUAMO"	,"EL MOLINO"	,"EL PASO"	,"EL PAUJIL"	,"EL PENON"	,"EL PENON"	,"EL PENON"	,"EL PEÑOL"	,"EL PINON"	,"EL PLAYON"	,"EL RETEN"	,"EL ROBLE"	,"EL ROSARIO"	,"EL TABLON"	,"EL TAMBO (CAUCA)"	,"EL TAMBO (NARINO)"	,"EL TARRA"	,"EL ZULIA"	,"ELIAS"	,"ENCINO"	,"ENCISO"	,"ENTRERRIOS"	,"ENVIGADO"	,"ESPINAL"	,"FACATATIVA"	,"FALAN"	,"FILADELFIA"	,"FILANDIA"	,"FIRAVITOBA"	,"FLANDES"	,"FLORENCIA"	,"FLORENCIA"	,"FLORESTA"	,"FLORIAN"	,"FLORIDA"	,"FLORIDA BLANCA"	,"FOMEQUE"	,"FONSECA"	,"FOSCA"	,"FRANCISCO PIZARRO"	,"FREDONIA"	,"FRESNO"	,"FRONTINO"	,"FUENTE DE ORO"	,"FUNDACION"	,"FUNES"	,"FUNZA"	,"FUQUENE"	,"FUSAGASUGA"	,"GACHALA"	,"GACHANCIPA"	,"GACHANTIVA"	,"GACHETA"	,"GALAN"	,"GALAPA"	,"GALERAS"	,"GAMA"	,"GAMARRA"	,"GAMBITA"	,"GAMEZA"	,"GARAGOA"	,"GARZON"	,"GENOVA"	,"GENOVA(NARINO)"	,"GETUCHA"	,"GIGANTE"	,"GINEBRA"	,"GIRALDO"	,"GIRARDOT"	,"GIRARDOTA"	,"GIRON"	,"GOMEZ PLATA"	,"GONZALEZ"	,"GRAMALOTE"	,"GRANADA"	,"GRANADA (ANTIOQUIA)"	,"GRANADA (META)"	,"GUACA"	,"GUACAMAYAS"	,"GUACARI"	,"GUACHETA"	,"GUACHUCAL"	,"GUADALUPE"	,"GUADALUPE (ANTIOQUIA"	,"GUADALUPE (HUILA)"	,"GUADUAS"	,"GUAITARILLA"	,"GUALMATAN"	,"GUAMAL (MAGDALENA)"	,"GUAMAL (META)"	,"GUAMO"	,"GUAPI"	,"GUAPOTA"	,"GUARANDA"	,"GUARNE"	,"GUASCA"	,"GUATAPE"	,"GUATAQUI"	,"GUATAVITA"	,"GUATEQUE"	,"GUATICA"	,"GUAVATA"	,"GUAYABAL SIQUIMA"	,"GUAYABETAL"	,"GUAYATA"	,"GUEPSA"	,"GUICAN"	,"GUTIERREZ"	,"HACARI"	,"HATILLO DE LOBA"	,"HATO"	,"HATO NUEVO"	,"HELICONIA"	,"HERRAN"	,"HERRERA"	,"HERVEO"	,"HISPANIA"	,"HOBO"	,"HONDA"	,"IBAGUE"	,"ICONONZO"	,"ILES"	,"IMUES"	,"INZA"	,"IPIALES"	,"IQUIRA"	,"ISNOS"	,"ITAGUI"	,"ITSMINA"	,"ITUANGO"	,"IZA"	,"JAMBALO"	,"JAMUNDI"	,"JARDIN"	,"JENESANO"	,"JERICO (ANTIOQUIA)"	,"JERICO (BOYACA)"	,"JERUSALEN"	,"JESUS MARIA"	,"JORDAN"	,"JUAN DE ACOSTA"	,"JUNIN"	,"JURADO"	,"LA APARTADA (LA FRON"	,"LA ARGENTINA"	,"LA BELLEZA"	,"LA CALERA"	,"LA CAPILLA"	,"LA CEJA"	,"LA CELIA"	,"LA CRUZ"	,"LA CUMBRE"	,"LA DORADA"	,"LA ESPERANZA"	,"LA ESTRELLA"	,"LA FLORIDA"	,"LA GLORIA"	,"LA JAGUA DE IBIRICO"	,"LA JAGUA DEL PILAR"	,"LA LLANADA"	,"LA MACARENA"	,"LA MAGDALENA"	,"LA MERCED"	,"LA MESA"	,"LA MONTANITA"	,"LA PALMA"	,"LA PAZ (CESAR)"	,"LA PAZ (SANTANDER)"	,"LA PENA"	,"LA PINTADA"	,"LA PLATA"	,"LA PLAYA"	,"LA SIERRA"	,"LA TEBAIDA"	,"LA TOLA"	,"LA UNION (ANTIOQUIA)"	,"LA UNION (NARINO)"	,"LA UNION (SUCRE)"	,"LA UNION (VALLE)"	,"LA URIBE"	,"LA UVITA"	,"LA VEGA"	,"LA VEGA."	,"LA VICTORIA"	,"LA VICTORIA (BOYACA)"	,"LA VIRGINIA"	,"LABATECA"	,"LABRANZAGRANDE"	,"LANDAZURI"	,"LEBRIJA"	,"LEIVA"	,"LEJANIAS"	,"LENGUAZAQUE"	,"LERIDA"	,"LIBANO (TOLIMA)"	,"LIBORINA"	,"LINARES"	,"LITORAL DE SAN JUAN"	,"LLORO"	,"LOPEZ"	,"LORICA"	,"LOS ANDES"	,"LOS CEDROS"	,"LOS CORDOBAS"	,"LOS PALMITOS"	,"LOS PATIOS (NORTE DE"	,"LOS SANTOS"	,"LOURDES"	,"LURUACO"	,"MACANAL"	,"MACARAVITA"	,"MACEO"	,"MACHETA"	,"MADRID (CUNDINAMARCA"	,"MAGANGUE"	,"MAGUI"	,"MAHATES"	,"MAICAO"	,"MAJAGUAL"	,"MALAGA"	,"MALAMBO"	,"MALLAMA"	,"MANATI"	,"MANAURE"	,"MANAURE BALCON DEL C"	,"MANIZALES"	,"MANTA"	,"MANZANARES"	,"MAPIRIPAN"	,"MARGARITA"	,"MARIA LA BAJA"	,"MARINILLA"	,"MARIPI"	,"MARIQUITA"	,"MARMATU"	,"MARQUETALIA"	,"MARSELLA"	,"MARULANDA"	,"MATANZA"	,"MATICURO"	,"MEDELLIN"	,"MEDINA"	,"MEDIO ATRATO"	,"MEDIO BAUDO"	,"MEDIO SAN JUAN"	,"MELGAR"	,"MERCADERES"	,"MESETAS"	,"MILAN"	,"MIRAFLORES (BOYACA)"	,"MIRANDA"	,"MISTRATO"	,"MOGOTES"	,"MOLAGAVITA"	,"MOMIL"	,"MOMPOS"	,"MONGUA"	,"MONGUI"	,"MONIQUIRA"	,"MONITOS"	,"MONTEBELLO"	,"MONTECRISTO"	,"MONTELIBANO"	,"MONTENEGRO"	,"MONTERIA"	,"MORALES (BOLIVAR)"	,"MORALES (CAUCA)"	,"MORELIA"	,"MORROA"	,"MOSQUERA (CUNDINAMAR"	,"MOSQUERA (NARINO)"	,"MOTAVITA"	,"MUNICIPIO DEL ATRATO"	,"MURILLO"	,"MURINDO"	,"MUSHAISA"	,"MUTATA"	,"MUTISCUA"	,"MUZO"	,"NARINO (ANTIOQUIA)"	,"NARINO (CUNDINAMARCA"	,"NATAGA"	,"NATAGAIMA"	,"NECHI"	,"NECOCLI"	,"NEIRA"	,"NEIVA"	,"NEMOCON"	,"NILO"	,"NIMAIMA"	,"NOBSA"	,"NOCAIMA"	,"NORCASIA"	,"NOVITA"	,"NUEVA GRANADA"	,"NUEVO COLON"	,"NUQUI"	,"OBANDO"	,"OCAMONTE"	,"OCANA"	,"OIBA"	,"OICATA"	,"OLAYA"	,"OLAYA HERRERA"	,"ONZAGA"	,"OPORAPA"	,"ORTEGA"	,"OSPINA"	,"OTANCHE"	,"OVEJAS"	,"PACHAVITA"	,"PACHO"	,"PACORA"	,"PADILLA"	,"PAEZ (BOYACA)"	,"PAEZ (CAUCA)"	,"PAICOL"	,"PAILITAS"	,"PAIME"	,"PAIPA"	,"PAJARITO"	,"PALERMO"	,"PALESTINA (CALDAS)"	,"PALESTINA (HUILA)"	,"PALMAR"	,"PALMAR DE LA VEGA"	,"PALMAS DEL SOCORRO"	,"PALMIRA"	,"PALMITO"	,"PALO CABILDO"	,"PALOCABILDO"	,"PAMPLONA"	,"PAMPLONITA"	,"PANDI"	,"PANQUEBA"	,"PANTANILLO"	,"PARAMO"	,"PARATEBUENO"	,"PASCA"	,"PASTO"	,"PATIA (EL BORDO)"	,"PAUNA"	,"PAYA"	,"PAZ DE RIO"	,"PEDRAZA"	,"PELAYA"	,"PENOL"	,"PENSILVANIA"	,"PEQUE"	,"PEREIRA"	,"PESCA"	,"PIEDECUESTA"	,"PIEDRAS"	,"PIENDAMO"	,"PIJAO"	,"PIJIÑO DEL CARMEN"	,"PINCHOTE"	,"PINILLOS"	,"PIOJO"	,"PISBA"	,"PITAL"	,"PITALITO"	,"PITINO DEL CARMEN"	,"PIVIJAY"	,"PIZARRO"	,"PLANADAS"	,"PLANETA RICA"	,"PLATO"	,"POLICARPA"	,"POLONUEVO"	,"PONEDERA"	,"POPAYAN"	,"POTOSI"	,"PRADERA"	,"PRADO"	,"PRIMAVERA"	,"PROVIDENCIA"	,"PUEBLO BELLO"	,"PUEBLO NUEVO"	,"PUEBLO RICO (ANTIOQU"	,"PUEBLO RICO (RISARAL"	,"PUEBLOVIEJO"	,"PUENTE NACIONAL"	,"PUERRES"	,"PUERTO BERRIO"	,"PUERTO BOYACA"	,"PUERTO COLOMBIA"	,"PUERTO CONCORDIA"	,"PUERTO ESCONDIDO"	,"PUERTO GAITAN"	,"PUERTO LIBERTADOR"	,"PUERTO LLERAS"	,"PUERTO LOPEZ"	,"PUERTO NARE"	,"PUERTO PARRA"	,"PUERTO RICO (CAQUETA"	,"PUERTO RICO (META)"	,"PUERTO SALGAR"	,"PUERTO SANTANDER"	,"PUERTO TEJADA"	,"PUERTO TRIUNFO"	,"PUERTO WILCHES"	,"PULI"	,"PUPIALES"	,"PURACE"	,"PURIFICACION"	,"PURISIMA"	,"QUEBRADANEGRA"	,"QUETAME"	,"QUIBDO"	,"QUIMBAYA"	,"QUINCHIA"	,"QUIPAMA"	,"QUIPILE"	,"RAGONVALIA"	,"RAMIRIQUI"	,"RAQUIRA"	,"REGIDOR"	,"REMEDIOS"	,"REMOLINO"	,"REPELON"	,"RESTREPO (META)"	,"RESTREPO (VALLE)"	,"RETIRO"	,"RICAURTE (CUNDINAMAR"	,"RICAURTE (NARINO)"	,"RIO DE ORO"	,"RIO NEGRO (SANTANDER"	,"RIO QUITO"	,"RIO VIEJO"	,"RIOBLANCO"	,"RIOFRIO"	,"RIOHACHA"	,"RIONEGRO"	,"RIOSUCIO (CALDAS)"	,"RIOSUCIO (CHOCO)"	,"RISARALDA (CALDAS)"	,"RIVERA"	,"ROBERTO PAYAN"	,"ROBLES (LA PAZ)"	,"ROLDANILLO"	,"RONCESVALLES"	,"RONDON"	,"ROSAS"	,"ROVIRA"	,"SABANA DE TORRES"	,"SABANAGRANDE"	,"SABANALARGA"	,"SABANALARGA (ANTIOQU"	,"SABANALARGA (ATLANTI"	,"SABANAS DE SAN ANGEL"	,"SABANETA"	,"SABOYA"	,"SACHICA"	,"SAHAGUN"	,"SALADOBLANCO"	,"SALAMINA (CALDAS)"	,"SALAMINA (MAGDALENA)"	,"SALAZAR"	,"SALDANA"	,"SALENTO"	,"SALGAR"	,"SAMACA"	,"SAMANA"	,"SAMANIEGO"	,"SAMPUES"	,"SAN  JOAQUIN"	,"SAN AGUSTIN"	,"SAN ALBERTO"	,"SAN ANDRES (ANTIOQUI"	,"SAN ANDRES (SANTANDE"	,"SAN ANDRES DE SOTAVE"	,"SAN ANTERO"	,"SAN ANTONIO"	,"SAN ANTONIO DEL TEQU"	,"SAN BENITO"	,"SAN BENITO ABAD"	,"SAN BERNANRDO"	,"SAN BERNARDO"	,"SAN BERNARDO"	,"SAN BERNARDO DEL VIE"	,"SAN CALIXTO"	,"SAN CARLOS (ANTIOQUI"	,"SAN CARLOS (CORDOBA)"	,"SAN CARLOS DE GUAROA"	,"SAN CAYETANO (CUNDIN"	,"SAN CAYETANO (NTE DE"	,"SAN CRISTOBAL"	,"SAN DIEGO"	,"SAN EDUARDO"	,"SAN ESTANISLAO"	,"SAN FERNANDO"	,"SAN FRANCISCO"	,"SAN FRANCISCO (CUNDI"	,"SAN GIL"	,"SAN JACINTO"	,"SAN JERONIMO"	,"SAN JOSE"	,"SAN JOSE DE FRAGUA"	,"SAN JOSE DE LA MONTA"	,"SAN JOSE DE MIRANDA"	,"SAN JOSE DE PARE"	,"SAN JOSE DEL PALMAR"	,"SAN JUAN BETULIA"	,"SAN JUAN DE ARAMA"	,"SAN JUAN DE NEPOMUCE"	,"SAN JUAN DE RIOSECO"	,"SAN JUAN DE URABA"	,"SAN JUAN DEL CESAR"	,"SAN JUAN DEL GUACAMA"	,"SAN JUANITO"	,"SAN LORENZO"	,"SAN LUIS (ANTIOQUIA)"	,"SAN LUIS (TOLIMA)"	,"SAN LUIS DE GACENO"	,"SAN MARCOS"	,"SAN MARTIN (CESAR)"	,"SAN MARTIN (META)"	,"SAN MARTIN DE LOBA"	,"SAN MATEO"	,"SAN MIGUEL"	,"SAN MIGUEL DE SEMA"	,"SAN ONOFRE"	,"SAN PABLO (BOLIVAR)"	,"SAN PABLO (NARINO)"	,"SAN PABLO DE BORBUR"	,"SAN PEDRO (ANTIOQUIA"	,"SAN PEDRO (SUCRE)"	,"SAN PEDRO (VALLE)"	,"SAN PEDRO DE CARTAGO"	,"SAN PEDRO URABA"	,"SAN PELAYO"	,"SAN RAFAEL"	,"SAN ROQUE"	,"SAN SEBASTIAN"	,"SAN SEBASTIAN DE BUE"	,"SAN SEBASTIAN DE BUE"	,"SAN VICENTE"	,"SAN VICENTE (CAQUETA"	,"SAN VICENTE DE CHUCU"	,"SAN VICENTE DEL CAGU"	,"SAN ZENON"	,"SANDONA"	,"SANTA ANA"	,"SANTA BARBARA (ANTIO"	,"SANTA BARBARA (NARIN"	,"SANTA BARBARA (SANTA"	,"SANTA CATALINA"	,"SANTA HELENA"	,"SANTA ISABEL"	,"SANTA LUCIA"	,"SANTA MARIA (BOYACA)"	,"SANTA MARIA (HUILA)"	,"SANTA MARTA"	,"SANTA ROSA (BOLIVAR)"	,"SANTA ROSA (CAUCA)"	,"SANTA ROSA DE CABAL"	,"SANTA ROSA DE OSOS"	,"SANTA ROSA DE VITERB"	,"SANTA ROSA DEL SUR"	,"SANTA SOFIA"	,"SANTACRUZ"	,"SANTANA"	,"SANTANDER DE QUILICH"	,"SANTIAGO (NTE DE SAN"	,"SANTO DOMINGO"	,"SANTO TOMAS"	,"SANTUARIO (ANTIOQUIA"	,"SANTUARIO (RISARALDA"	,"SAPUYES"	,"SARDINATA"	,"SASAIMA"	,"SATIVANORTE"	,"SATIVASUR"	,"SEGOVIA"	,"SESQUILE"	,"SEVILLA"	,"SIACHOQUE"	,"SIBATE"	,"SILOS"	,"SILVANIA"	,"SILVIA"	,"SIMACOTA"	,"SIMIJACA"	,"SIMITI"	,"SINCE"	,"SINCELEJO"	,"SIPI"	,"SITIONUEVO"	,"SOACHA"	,"SOATA"	,"SOCHA"	,"SOCORRO"	,"SOCOTA"	,"SOGAMOSO"	,"SOLANO"	,"SOLEDAD"	,"SOLITA"	,"SOMONDOCO"	,"SONSON"	,"SOPETRAN"	,"SOPLAVIENTO"	,"SOPO"	,"SORA"	,"SORACA"	,"SOTAQUIRA"	,"SOTARA"	,"SUAITA"	,"SUAN"	,"SUAREZ"	,"SUAREZ"	,"SUAZA"	,"SUBACHOQUE"	,"SUCRE"	,"SUCRE (SANTANDER)"	,"SUCRE (SUCRE)"	,"SUESCA"	,"SUPATA"	,"SUPIA"	,"SURATA"	,"SUSA"	,"SUSACON"	,"SUTAMARCHAN"	,"SUTATAUSA"	,"SUTATENZA"	,"TABIO"	,"TADO"	,"TALAIGUA NUEVO"	,"TAMALAMEQUE"	,"TAMARA (BOYACA)"	,"TAMESIS"	,"TAMINANGO"	,"TANGUA"	,"TARAZA"	,"TARQUI"	,"TARSO"	,"TASCO"	,"TAUSA"	,"TEDRAMA"	,"TELLO"	,"TENA"	,"TENERIFE"	,"TENJO"	,"TENZA"	,"TEROEL"	,"TESALIA"	,"TIBACUY"	,"TIBANA"	,"TIBASOSA"	,"TIBIRITA"	,"TIBU"	,"TIERRALTA"	,"TIMANA"	,"TIMBIO"	,"TIMBIQUI"	,"TINJACA"	,"TIPACOQUE"	,"TIQUISIO"	,"TITIRIBI"	,"TOCA"	,"TOCAIMA"	,"TOCANCIPA"	,"TOGUI"	,"TOLEDO (ANTIOQUIA)"	,"TOLEDO (NTE DE SANTA"	,"TOLU"	,"TOLUVIEJO"	,"TONA"	,"TOPAGA"	,"TOPAIPI"	,"TORIBIO"	,"TORO"	,"TOTA"	,"TOTORO"	,"TRUJILLO"	,"TUBARA"	,"TULUA"	,"TUMACO"	,"TUNJA"	,"TUNUNGUA"	,"TUQUERRES"	,"TURBACO"	,"TURBANA"	,"TURBO"	,"TURMEQUE"	,"TUTA"	,"TUTASA"	,"UBALA"	,"UBAQUE"	,"UBATE"	,"ULLOA"	,"UMBITA"	,"UNE"	,"UNGUIA"	,"URAMITA"	,"URIBIA"	,"URRAO"	,"URUMITA"	,"USIACURI"	,"UTICA"	,"VALDIVIA"	,"VALENCIA"	,"VALLE DE SAN JUAN"	,"VALLE SAN JOSE"	,"VALLEDUPAR"	,"VALPARAISO (ANTIOQUI"	,"VALPARAISO (CAQUETA)"	,"VEGACHI"	,"VELEZ"	,"VENADILLO"	,"VENECIA"	,"VENECIA (CUNDI)"	,"VENTAQUEMADA"	,"VERGARA"	,"VERSALLES"	,"VETAS"	,"VIANI"	,"VICTORIA"	,"VIGIA DEL FUENTE"	,"VIJES"	,"VILLA DE LEIVA"	,"VILLA DEL ROSARIO"	,"VILLA RICA"	,"VILLACARO"	,"VILLAGOMEZ"	,"VILLAHERMOSA"	,"VILLAMARIA"	,"VILLANUEVA (BOLIVAR)"	,"VILLANUEVA (LA GUAJI"	,"VILLANUEVA (SANTANDE"	,"VILLAPINZON"	,"VILLARICA"	,"VILLAVICENCIO"	,"VILLAVIEJA"	,"VILLETA"	,"VIOTA"	,"VIRACACHA"	,"VISTA HERMOSA"	,"VITERBO"	,"YACOPI"	,"YACUANQUER"	,"YAGUARA"	,"YALI"	,"YARUMAL"	,"YOLOMBO"	,"YONDO"	,"YOTOCO"	,"YUMBO"	,"YOPAL"	,"ZAMBRANO"	,"ZAPATOCA"	,"ZAPAYAN"	,"ZARAGOZA (ANTIOQUIA)"	,"ZARZAL"	,"ZETAQUIRA"	,"ZIPACON"	,"ZIPAQUIRA"	,"ZONA BANANERA"
]
   
departamento_dipser:string[]=["ANTIOQUIA"	,"ATLANTICO"	,"BOGOTA D.C"	,"BOLIVAR"	,"BOYACA"	,"CALDAS"	,"CAQUETA"	,"CAUCA"	,"CESAR"	,"CORDOBA"	,"CUNDINAMARCA"	,"CHOCO"	,"HUILA"	,"GUAJIRA"	,"MAGDALENA"	,"META"	,"NARIÑO"	,"NORTE DE SANTANDER"	,"QUINDIO"	,"RISARALDA"	,"SANTANDER"	,"SUCRE"	,"TOLIMA"	,"VALLE DEL CAUCA"	,"ARAUCA"	,"CASANARE"	,"PUTUMAYO"	,"SAN ANDRES Y PROVIDENCIA"	,"AMAZONAS"	,"GUAINIA"	,"GUAVIARE"	,"VAUPES"	,"VICHADA"
]

caracteristicas_del_lugar:string[]=["Aulas "	,"Almacenes/ bodegas"	,"Alojamiento/ casinos"	,"Alta montaña/ páramo"	,"Áreas de instrucción/ pistas"	,"Angares"	,"Baños"	,"Base de patrullas móviles"	,"Bases fijas"	,"Bunker"	,"Campo abierto"	,"Caniles, pesebreras/ granjas"	,"Centros educativos"	,"Centros de reclusión "	,"Centros vacacionales"	,"Cocinas/ ranchos de tropa"	,"Corredores, pasillos / plazoletas"	,"Dispensarios de salud/ hospitales/ centros médico"	,"Escaleras"	,"Escenarios deportivos"	,"Garitas"	,"Helipuertos/aeropuertos"	,"Medios transporte de personas "	,"Medios de transporte de cargas"	,"Oficinas"	,"Otro lugar fuera de las instalaciones militares"	,"Polígono"	,"Puesto de mando"	,"Ríos, mar, quebradas, lagos, piscinas."	,"Selva/zona boscosa"	,"Subestaciones eléctricas"	,"Talleres / Astilleros"	,"Vivienda/ casa de habitación"	,"Vivienda de otra persona"	,"Vías dentro de instalaciones militares"	,"Vía o camino "	,"Zonas de recolección de residuos"	,"Polvorines"	,"Desierto"	,"Montaña"
]
  
gr_cdte_un:string[]=["GR"	,"MG"	,"BG"	,"CR"	,"TC"	,"MY"	,"CT"	,"TE"	,"ST"	,"SMC"	,"SM"	,"SP"	,"SV"	,"SS"	,"CP"	,"CS"	,"C3","DGSLP", "SLP","DG","SL18","SL12", "----"]
gr_cdte:string[]=["GR"	,"MG"	,"BG"	,"CR"	,"TC"	,"MY"	,"CT"	,"TE"	,"ST"	,"SMC"	,"SM"	,"SP"	,"SV"	,"SS"	,"CP"	,"CS"	,"C3","DGSLP", "SLP","DG","SL18","SL12", "----", "BANDERA DE GUERRA"]
arma:string[]=["ING", "INF", "ART", "CAB", "COM","LOG", "AVI", "INT","IMI", "FES", "N/A"]
meses_dipse:string[]=["MENOS DE UN MES"	,"0 MESES"	,"1 MES"	,"2 MESES"	,"3 MESES"	,"4 MESES"	,"5 MESES"	,"6 MESES"	,"7 MESES"	,"8 MESES"	,"9 MESES"	,"10 MESES"	,"11 MESES"	,"0 AÑOS"	,"1 AÑO"	,"2 AÑOS "	,"3 AÑOS "	,"4 AÑOS "	,"5 AÑOS"	,"6 AÑOS"	,"7 AÑOS "	,"8 AÑOS"	,"9 AÑOS"	,"10 AÑOS"	,"11 AÑOS"	,"12 AÑOS"	,"13 AÑOS"	,"14 AÑOS"	,"15 AÑOS"	,"16 AÑOS"	,"17 AÑOS"	,"18 AÑOS"	,"19 AÑOS"	,"20 AÑOS"	,"21 AÑOS"	,"22 AÑOS"	,"23 AÑOS"	,"24 AÑOS"	,"25 AÑOS"	,"26 AÑOS"	,"27 AÑOS"	,"28 AÑOS"	,"29 AÑOS"	,"30 AÑOS"	,"31 AÑOS"	,"32 AÑOS"	,"33 AÑOS"	,"34 AÑOS"	,"35 AÑOS"	,"36 AÑOS"	,"37 AÑOS"	,"38 AÑOS"	,"39 AÑOS"	,"40 AÑOS"	,"41 AÑOS"	,"42 AÑOS"	,"43 AÑOS"	,"44 AÑOS"	,"45 AÑOS"	,"46 AÑOS"	,"47 AÑOS"	,"48 AÑOS"	,"49 AÑOS"	,"50 AÑOS"
]

atencion_imediata:string[]=["Enfermero militar o Socorrista militar "	,"Dispensario médico "	,"Centro médico municipal"	,"Hospital NO Militar o NO Policial"	,"Hospital Militar/Central o regional /Clínica de policía / Hospital naval"	,"Socorrista o Brigadista de la unidad"	,"Primeros auxilios"	,"Otro socorrista o brigadista"	,"No aplica"
]

genero_dipse:string[]=["MASCULINO"	,"FEMENINO"]

lugar_afectacion:string[]=["Cabeza"	,"Cuello"	,"Tronco"	,"Miembro_superior"	,"Miembro_inferior"	,"Ubicaciones_multiples"	,"Lesiones_generales"]
afectacion_espeficica:string[]=["11 - Región craneana (cráneo, cerebro, cuero cabelludo)"	,"12 - Ojo (con inclusión de la órbita y del nervio óptico)"	,"13 - Oreja"	,"14 - Boca (con inclusión de los labios, dientes y lengua)"	,"15 - Nariz"	,"16 - Cara, ubicaciones no clasificadas bajo otros epígrafes"	,"18 - Cabeza, ubicaciones múltiples"	,"19 - Cabeza, ubicación no presisada"	,"21 - CUELLO"	,"31 - Espalda (columna vertebral y músculos adyacentes, médula espinal)"	,"32 - Tórax (costillas, esternón, órganos internos del tórax)"	,"33 - Abdomen (con inclusión de los organos internos)"	,"34 - Pelvis"	,"38 - Tronco, ubicaciones múltiples"	,"39 - Tronco, ubicación no precisada"	,"41 - Hombro (con inclusión de la clavicula y del omoplato)"	,"42 - Brazo"	,"43 - Codo"	,"44 - Antebrazo"	,"45 - Muñeca"	,"46 - Mano (A excepción de los dedos solos)"	,"47 - Dedos"	,"48 - Miembro superior, ubicaciones múltiples"	,"49 - Miembro superior, ubicación no precisada"	,"51 - Cadera"	,"52 - Muslo"	,"53 - Rodilla"	,"54 - Pierna"	,"55 - Tobillo"	,"56 - Pie (A excepción de los dedos solos)"	,"57 - Dedos, de los pies"	,"58 - Miembro inferior, ubicaciones múltiples"	,"59 - Ubicación no precisada"	,"61 - Cabeza y tronco, cabeza y uno o varios miembros"	,"62 - Tronco y uno o varios miembros"	,"63 - Un miembro superior y un miembro inferior o mas de dos miembros"	,"68 - Otras ubicaciones múltiples"	,"69 - Ubicaciones múltiples no precisadas"	,"71 - Aparato circulatorio en general"	,"72 - Aparato respiratorio en general"	,"73 - Aparato digestivo en general"	,"74 - Sistema nervioso en general"	,"78 - Otras lesiones generales"	,"79 - Lesiones generales no precisadas"
]
clase_novedad:string[]=["ACCIDENTES_DE_AVIACIÓN"	,"ACCIDENTES_ARMA_DE_FUEGO"	,"AGRESIONES"	,"ACCIDENTES_DE_TRÁNSITO"	,"LESIONES_AUTOINFLIGIDAS"	,"LESIONES_POR_ACCIÓN_DIRECTA_DEL_ENEMIGO"	,"HIGIENE_INDUSTRIAL"	,"RIESGO_DE_ORIGEN_NATURAL"	,"SEGURIDAD_INDUSTRIAL"	,"ACCIDENTES_POR_INMERSIÓN"	,"ASFIXIA_MECANICA"	,"LESIONES_POR_ANIMALES"	,"MUERTE_POR_ENFERMEDAD"	,"ACCIDENTE_POR_QUEMADURAS"	,"TEMPERATURA_EXTREMA"
]
tipo_novedad:string[]=["ACCIDENTES AÉREOS"	,"ACCIDENTE RELACIONADO CON EL VUELO"	,"ACCIDENTE FRATRICIDA"	,"ACCIDENTE CON MUNICIONES Y EXPLOSIVOS"	,"DISPARO ACCIDENTAL"	,"AGRESIÓN EXTERNA"	,"AGRESIÓN INTERNA"	,"NEUTRALIZACIÓN"	,"ACCIDENTE DE TRÁNSITO BICICLETA"	,"ACCIDENTE TRÁNSPORTE COMERCIAL MOTO"	,"ACCIDENTE TRÁNSPORTE COMERCIAL VEHÍCULO"	,"ACCIDENTE DE TRÁNSITO MAQUINARIA INGENIEROS"	,"ACCIDENTE DE TRANSITO MOTO DE USO OFICIAL"	,"ACCIDENTE DE TRANSITO MOTO PARTICULAR"	,"ACCIDENTE DE TRANSITO PEATÓN MOTO"	,"ACCIDENTE DE TRANCITO PEATÓN VEHICULO"	,"ACCIDENTE DE TRANSITO VEHICULO DE USO OFICIAL"	,"ACCIDENTE DE TRANSITO VEHICULO PARTICULAR"	,"INTENTO DE AUTO ELIMINACIÓN"	,"INUTILIZACIÓN VOLUNTARIA"	,"AUTOELIMINACIÓN"	,"ARTEFACTO EXPLOSIVO IMPROVISADO"	,"ENFRENTAMIENTO"	,"ENVENENAMIENTO"	,"FRANCOTIRADORES"	,"MINAS"	,"PISA SUAVES"	,"LESIONES POR FACTORES BIOMECANICOS"	,"LESIONES POR FACTORES  DE RIESGOS BIOLÓGICOS"	,"LESIONES POR FACTORES DE RIESGOS FÍSICOS"	,"LESIONES POR FACTORES DE RIESGOS QUIMICOS"	,"ACCIDENTE POR AVALANCHAS"	,"GRANIZADA"	,"INUNDACIONES"	,"ACCIDENTE POR DESCARGAS ATMOSFÉRICAS (RAYOS)"	,"SISMOS"	,"TERREMOTOS"	,"TSUNAMI"	,"VENDAVALES"	,"Deslisamiento de rocas o terreno"	,"Tormenta"	,"ACCIDENTES MECÁNICOS"	,"ACCIDENTE POR CAÍDAS DE ALTURAS"	,"ACCIDENTES POR CAIDAS MISMO NIVEL"	,"ACCIDENTES DEPORTIVOS"	,"ACCIDENTES POR CHOQUES ELÉCTRICOS"	,"ACCIDENTES LOCATIVOS"	,"ACCIDENTES POR INMERSIÓN"	,"ASFIXIA MECÁNICA"	,"MORDEDURAS"	,"OTRAS LESIONES POR ANIMALES"	,"PICADURAS"	,"MUERTE POR ENFERMEDAD COMÚN"	,"MUERTE POR ENFERMEDAD LABORAL"	,"QUEMADURAS"	,"GOLPE DE CALOR"	,"HIPOTERMIA"
]

si_no:string[]=["SI", "NO"]
identificacion_peligro:string[]=["Fuente"	,"Situación"	,"Acto"	,"Evento fisico de origen natural"	,"Evento fisico de origen antropico"
]

agente_de_la_lesion:string[]=["Máquinas_y_o_equipos"	,"Medios_de_transporte_de_cargas"	,"Medios_de_transporte_de_personas"	,"Herramientas_implementos_o_utensilios"	,"Aparatos"	,"Materiales_o_sustancias"	,"Radiaciones_ionizantes_y_no_ionizantes "	,"Ambiente_de_trabajo"	,"Animales_y_sus_partes"	,"Municiones"	,"Explosivos"	,"Fuentes_hídricas"	,"Fenómenos_naturales"	,"Microorganismos "	,"Plantas_vegetales"	,"Personas "	,"Comestibles_y_bebidas"	,"Otros_agentes "]

mecanismo_de_la_lesion:string[]=["Bruñidoras, pulidoras, lijadoras, esmeriladoras"	,"Cepilladoras, planeadoras, trompos y otras máquinas para trabajo de la madera"	,"Cizallas, cortadoras, rebanadoras. (Cortadoras de disco), guillotinas"	,"Electrodomésticos "	,"Equipos de calefacción o refrigeración"	,"Equipos de impresión "	,"Equipos de izaje/movilización de cargas"	,"Equipos de soldadura"	,"Equipos de transmisión de fuerza mecánica. (Ej.: cadenas, poleas)"	,"Generadores de energía"	,"Herramientas manuales mecanizadas  (ej. pulidora)"	,"Inyectoras, extrusoras, sopladoras de plásticos"	,"Laminadoras, trefiladoras"	,"Máquina cortadora de tela"	,"Máquinas agrícolas"	,"Máquinas de coser, hilvanar"	,"Máquinas de imprenta"	,"Máquinas de tejer, hacer punto o hilar"	,"Máquinas empacadoras, selladoras"	,"Máquinas industriales (confección de uniformes, textiles, para fabricación de partes"	,"Máquinas para el trabajo del metal"	,"Máquinas para el trabajo en las minas"	,"Máquinas para fundir, forjar y máquinas fijas automáticas para soldar metales"	,"Máquinas para minería y túneles"	,"Máquinas para taladrar, barrenar, tornear (roscadora, fresadora y cepilladora para metales, limadora, molinos, rectificadoras)"	,"Máquinas para trabajar la madera y otros materiales similares"	,"Máquinas para trabajos en obras civiles y construcción"	,"Máquinas tamizadoras y separadoras"	,"Molinos eléctricos"	,"Motores, turbinas (vapor, combustión interna, etc.)."	,"Planchadoras"	,"Prensas, troqueladoras, estampadoras, elaboradoras de puntillas, tapadoras, cadenas, etc."	,"Pulidoras, gratas, brilladoras electrices"	,"Sierras"	,"Sierras, máquinas sinfín, circular"	,"Sistemas de transmisión (poleas, engranajes)"	,"Taladros eléctricos"	,"Otras máquinas "	,"Grúas, ascensores, montacargas, camiones, planchones) "	,"Grúas"	,"Ascensores"	,"Montacargas"	,"Camiones"	,"Planchones"	,"Elevadores neumáticos"	,"Elevadores de cadena, diferencial de cadena"	,"Elevadores eléctricos"	,"Pescante de malacate, malacate de poste o de pértiga"	,"Gatos (mecánicos, hidráulicos, neumáticos, etc.)."	,"Ganchos para transporte de cargas"	,"Palas, dragas"	,"Vehículo de tracción animal"	,"Otro medio de transporte de cargas"	,"Aeronave"	,"Ascensor"	,"Animal de monta"	,"Artefactos navales"	,"Automóvil "	,"Bicicleta"	,"Buque"	,"Bus"	,"Camioneta "	,"Ciclomotores"	,"Cuatrimoto"	,"Lancha"	,"Moto"	,"Tren"	,"Vehículo de tracción animal"	,"Otro medio de transporte de personas"	,"Adornos, accesorios "	,"Broca"	,"Cajas, barriles, envases, paquetes, vasos  (vacíos o llenos)"	,"Cepillos, garlopas"	,"Cincel, escoplo, formón"	,"Elemento corto punzante: cuchillo, hacha, jeringa, vidrio, machete, bisturí, tijera, etc."	,"Escaleras  portátiles"	,"Herramientas manuales NO electicas y NO mecanizadas: em destornillador, pinza, martillo"	,"Herramientas para labrar la tierra: azadón, pala, etc. "	,"Herramientas, implementos o utensilios  de racho o cocina"	,"Herramientas, implementos o utensilios de aseo, canecas, cajas, entre otros"	,"Herramientas, implementos o utensilios de oficinas"	,"Lapicero"	,"Lima"	,"Llaves para tuercas y para tubos"	,"Microscopio"	,"Palanca, barra"	,"Papel y artículos de pulpa o fibra"	,"Productos de madera (Troncos, tablas)"	,"Productos textiles"	,"Punzones"	,"Serrucho, segueta, corta vidrio "	,"Soga/ lazo/cinturón/reata o similares"	,"Taladro manual"	,"Tubos, tanques (vacíos o llenos)"	,"Vestuario, trajes, calzado"	,"Otras herramientas, implementos o utensilios"	,"Andamio"	,"Aparatos eléctricos, no especificados en otra parte"	,"Aparatos magnéticos y electrolíticos"	,"Artefactos para calefacción"	,"Autoclave"	,"Caldera"	,"Cilindros de oxígeno y acetileno"	,"Conductores"	,"Equipo de buzo"	,"Equipos que usan fuego o calor (ej.. Estufas, hornos, sopletes)"	,"Escaleras móviles, rampas móviles"	,"Generadores"	,"herramientas eléctricas manuales: pulidora, taladro, etc. "	,"Líneas de presión  (mangueras o tubos - para líquidos presurizados, gases o vapores)"	,"Motores eléctricos"	,"Recipientes a presión,  no especificados en otra parte"	,"Recipientes presurizados (para gases o líquidos),  compresor"	,"Reóstato, aparatos de arranque y control, condensadores, rectificadores, acumuladores"	,"Tableros de distribución, barras colectoras, interruptores, fusibles, cortadores de circuitos, cajas de distribución, etc."	,"Transformadores, convertidores"	,"Ventiladores"	,"Otros aparatos"	,"Artículos de cerámica, ladrillos"	,"Artículos de metal  (agujas, Platinas, varillas, etc.)"	,"Artículos de vidrio: botellas, vasos, etc."	,"Artículos plásticos, caucho"	,"Carbón, petróleo y sus derivados, aceites vegetales"	,"Carrotermo / carros para movilización de elementos de comedor o bodega"	,"Coberturas para pisos, carpetas, alfombras, esteras, etc."	,"Combustibles"	,"Desechos industriales, escombros"	,"Equipo para alumbrado, lámparas, bombillas, etc."	,"Fragmentos volantes o proyectados "	,"Jabones, detergentes, compuestos para limpieza"	,"Mostradores, bancos de trabajo, etc."	,"Muebles de alojamientos"	,"Muebles de oficina"	,"Muebles en centros de atención en salud"	,"Partículas metálicas, polvos minerales"	,"Productos minerales (ej.. Arena, piedras)"	,"Otras sustancias químicas: sólidos, líquidos, gases"	,"Toxico/ veneno"	,"Vapor de agua"	,"Veladoras"	,"Vidrio"	,"Otro tipo de materiales y sustancias."	,"Radiaciones ionizantes(rayos x, rayos gama, beta) "	,"Radiaciones no ionizantes (radiaciones solares -UV, electromagnéticas, soldadura, laser, infrarrojos, entre otros) "	,"Fuentes radioactivas"	,"Otras radiaciones"	,"Aceras, senderos, pasillos (Al aire libre)"	,"Agua"	,"Alojamiento"	,"Altura"	,"alumbrado"	,"Baños"	,"Calles, caminos, carreteras"	,"Carencia o exceso de oxígeno"	,"Comedores"	,"Escaleras, escalones "	,"Espacios reducidos / espacios confinados"	,"Frío /calor"	,"Fuego "	,"Paredes"	,"Pasillos o plataformas (superficies elevadas permanentes)."	,"Piso (de un edificio, una mina, un vehículo, un andamio, etc.)"	,"Presión atmosférica anormal"	,"Puertas "	,"Rampas"	,"Redes eléctricas"	,"Revestimientos de galerías, de túneles, de zanjas, de frentes de minas"	,"Ruido"	,"Superficies de trabajo"	,"Techos"	,"Tejados y cubiertas internas o externas"	,"Temperaturas extremas"	,"Terrenos (al aire libre)."	,"Ventanas"	,"Ventilación"	,"Zona de cocina"	,"Otras condiciones del ambiente de trabajo"	,"Productos animales ej.. secreciones (excluye alimentos) "	,"animales vivos: insectos"	,"animales vivos: semovientes"	,"animales vivos: reptiles"	,"animales vivos: pescados"	,"animales vivos: anfibios"	,"animales vivos: aves"	,"Otros animales vivos "	,"Huesos"	,"Secreciones"	,"Plumas"	,"Pieles, cerdas, lana, etc.  (en estado bruto)"	,"Cueros y pieles curtidas"	,"Otras partes de animales"	,"Municiones de arma larga de dotación de la fuerza"	,"Municiones de arma corta de dotación de la fuerza"	,"Municiones de arma larga de otras personas"	,"Municiones de arma corta de dotación de otras personas"	,"Dinamita"	,"Gel"	,"Agentes explosivos (ej. Anfo)"	,"Otros explosivos"	,"Depósito/Fuente de agua u otro líquido"	,"Lago, laguna, embalse, estero, manglar"	,"Pozo de agua"	,"Albercas, tanques, piscinas"	,"Rio / quebrada"	,"Mar"	,"Otras fuentes hídricas"	,"Rayos"	,"Inundaciones"	,"Tsunami"	,"Sismo / temblor / terremoto"	,"Huracán,  vendaval"	,"Erupción volcánica"	,"Avalancha"	,"Granizadas, lluvias "	,"Otros fenómenos naturales"	,"Hongos"	,"Virus"	,"Bacterias"	,"Otros microorganismos"	,"Plantas, vegetación "	,"Arboles "	,"Ramas y material vegetal en descomposición "	,"Plantas venenosas, espinosas"	,"Otros tipo de plantas"	,"Personas de la institución "	,"Civiles "	,"Miembros de otras fuerzas o policía"	,"Enemigos"	,"Otros tipo de personas"	,"Comestibles frescos de origen animal (pescado, carne, huevos)"	,"Comestibles frescos de origen vegetal (frutas, verduras, cereales) entre otros"	,"Comestibles procesados o fabricados: enlatados, fritos, horneados, entre otros"	,"Bebidas procesadas: licor / gaseosas"	,"Agua"	,"Jugos frescos de frutas"	,"Otros comestibles"	,"Otras bebidas"	,"Especifique cuál"
]

informacion_vehiculo:string[]=["Motocicleta "	,"Carro"	,"Bicicleta"]
tipo_vehiculo:string[]=["Vehículo oficial"	,"Vehículo particular"
]

  constructor() { }
  lsta:{} = JSON.parse(sessionStorage.getItem("unidades")!)
  enemigo:{} = JSON.parse(sessionStorage.getItem("enemigo")!)
  op_mayor:{} = JSON.parse(sessionStorage.getItem("op_mayor")!)
  estrategia:{} = JSON.parse(sessionStorage.getItem("estrategia")!)
  tipo_operacion:{} = JSON.parse(sessionStorage.getItem("tipo_operacion")!)
  // eventos_div:{}=JSON.parse(sessionStorage.getItem("eventos")!)
  // eventos_divicionarios:string[]=[]

  lat:string[]=["LN","LS"]
  lot:string[]=["LW","LO"]

  division : string[] = [];
  unidad_hija: string[] = []

  departamentos : string[] = []
  amenaza : string[] = []
  op_mayores:string[]=[]

  estrategia_2:string[]=[]
  tipo_operacion_2:string[]=[]

  listados:string[]=["ASESINADOS", "HERIDOS"]
  amenaza_eventos:string[]=["AUTODEFENSAS GAITANISTAS DE COLOMBIA (AGC)","AUTODEFENSAS CONQUISTADORAS DE LA SIERRA NEVADA (ACSN)","SEGUNDA MARQUETALIA (SM)", "GAO-ELN", "EMC - FARC-EP"]
  amenazados_aelertas:string[]=["EJC","ARC","FAC", "POLICIA", "ENTIDADES GUBERNAMENTALES", "ENTIDADES CIVILES", "COMUNIDAD CIVIL", "COMUNIDAD INDIGENA", "MINORIAS", "OTROS", "N/A"]
  eventos:string[]=["ae"]

  gao_:string[]=["GAO-r", "GAO-CG", "GAO-ELN", "GDO", "DELINCUENCIA", "NARCOTRAFICO", "NO APLICA"]
  tipo_unidad:string[]=["COMPAÑIA", "PELOTON", "SECCION", "ESCUADRA", "BASE MILITAR", "PDMAT", "PMAD"]
  unidades:{} = this.lsta
  unidad:string

  result = Object.keys(this.unidades).map((key) => {
    return { [key]: this.unidades[key as keyof typeof this.unidades] };
  });

  enemigos = Object.keys(this.enemigo).map((key) => {
    return { [key]: this.enemigo[key as keyof typeof this.enemigo] };
  });
  
  op_mayore = Object.keys(this.op_mayor).map((key) => {
    return { [key]: this.op_mayor[key as keyof typeof this.op_mayor] };
  });
  estrategia_ = Object.keys(this.estrategia).map((key) => {
    return { [key]: this.estrategia[key as keyof typeof this.estrategia] };
  });

  tipo_operacion_ = Object.keys(this.tipo_operacion).map((key) => {
    return { [key]: this.tipo_operacion[key as keyof typeof this.tipo_operacion] };
  });

   duplicados(){
    for (let x in this.result){
      let dato = this.result[x]
      for(let j in dato){
        this.unidad = dato[j][0]
        if (!this.division.includes(this.unidad)) {
          this.division.push(this.unidad )
        }
      }
    }
    this.division.sort()
    return this.division
  }
  
  departamentos_unicos(){
    for (let x in this.result){
      let dato = this.result[x]
      for(let j in dato){
        this.unidad = dato[j][4]
        if (!this.departamentos.includes(this.unidad)) {
          this.departamentos.push(this.unidad )
        }
      }
    }
    this.departamentos.sort()
    return this.departamentos
  }
     
  amenaza_select(){
    for (let x in this.enemigos){
      let dato = this.enemigos[x]
      for(let j in dato){
        this.unidad = dato[j][0]
        if (!this.amenaza.includes(this.unidad)) {
          this.amenaza.push(this.unidad )
        }
      }
    }
    this.amenaza.sort()
    return this.amenaza
  }
  
  tipo_operacion_f(){
    for (let x in this.tipo_operacion_){
      let dato = this.tipo_operacion_[x]
      for(let j in dato){
        this.unidad = dato[j][0]
        if (!this.tipo_operacion_2.includes(this.unidad)) {
          this.tipo_operacion_2.push(this.unidad )
        }
      }
    }
    this.tipo_operacion_2.sort()
    return this.tipo_operacion_2
  } 

  estrategia_f(){
    for (let x in this.estrategia_){
      let dato = this.estrategia_[x]
      for(let j in dato){
        this.unidad = dato[j][0]
        if (!this.estrategia_2.includes(this.unidad)) {
          this.estrategia_2.push(this.unidad )
        }
      }
    }
    this.estrategia_2.sort()
    return this.estrategia_2
  } 
  op_mayores_f(){
    for (let x in this.op_mayore){
      let dato = this.op_mayore[x]
      for(let j in dato){
        this.unidad = dato[j][0]
        if (!this.op_mayores.includes(this.unidad)) {
          this.op_mayores.push(this.unidad )
        }
      }
    }
    this.op_mayores.sort()
    return this.op_mayores
  }
  unidades_filtradas(unidad_hija:string, index_evaluar:number, index_evaluado:number){
    this.unidad_hija = []
    for (let x in this.result){
      let dato = this.result[x]
      for(let j in dato){
        
        if (dato[j][index_evaluar] === unidad_hija) {

          this.unidad = dato[j][index_evaluado] 
         if (!this.unidad_hija.includes(this.unidad)) {
          this.unidad_hija.push(this.unidad )
        }
        }

      }
      
    }
    this.unidad_hija.sort()

    return this.unidad_hija
  }
       
  array_listados(listado:{}){
    const resultados = Object.keys(listado).map((key) => {
      return { [key]: listado[key as keyof typeof listado] };
    });

    const listado_control:String[]=[]
    for (let x in resultados){
      const dato = resultados[x]
      for(let j in dato){
        this.unidad = dato[j]
        listado_control.push(this.unidad )
      }
    }
    return listado_control
  }

}
